# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'

import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()

a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()

a2 = np.array([[1,4,5],
               [7,2,8]])

# Create a 3-dimensional Numpy array using np.array()

a3 = np.array([[[4,6,8],
               [2,9,1]],
              [[12,44,5],
               [5,0,6]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array

a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array

a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  4  5
1  7  2  8

In [8]:
# Create an array of shape (10, 2) with only ones

ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros

zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3

three_array = np.arange(0, 100, 3)
three_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

random_int = np.random.randint(0,10, size=(7,2))
random_int

array([[1, 5],
       [9, 5],
       [9, 7],
       [5, 7],
       [7, 7],
       [7, 2],
       [5, 7]])

In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

random_float = np.random.random((3,5))
random_float

array([[0.17382009, 0.66783015, 0.30738298, 0.15941761, 0.23340814],
       [0.42492663, 0.31456087, 0.96794862, 0.96033181, 0.96296313],
       [0.21498973, 0.95336913, 0.58917132, 0.61822779, 0.62099748]])

In [18]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

random_int = np.random.randint(10, size = (4,6))
random_int

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

In [24]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

random_int = np.random.randint(1, 10, size = (3,7))
print(random_int)
# Find the unique numbers in the array you just created

unique_random_int = np.unique(random_int)
unique_random_int

[[7 1 1 9 9 4 9]
 [3 7 6 8 9 5 1]
 [3 8 6 8 9 4 1]]


array([1, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Find the 0'th index of the latest array you created

random_int[0]

array([7, 1, 1, 9, 9, 4, 9])

In [26]:
# Get the first 2 rows of latest array you created

random_int[:2]

array([[7, 1, 1, 9, 9, 4, 9],
       [3, 7, 6, 8, 9, 5, 1]])

In [43]:
# Get the first 2 values of the first 2 rows of the latest array

random_int[:2, :2]

array([[7, 1],
       [3, 7]])

In [46]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

random_int = np.random.randint(10, size = (3,5))
print(random_int)

ones = np.ones((3,5))
ones

[[7 4 3 1 5]
 [5 0 8 5 2]
 [3 3 2 9 2]]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
# Add the two arrays together

random_int + ones

array([[ 8.,  5.,  4.,  2.,  6.],
       [ 6.,  1.,  9.,  6.,  3.],
       [ 4.,  4.,  3., 10.,  3.]])

In [49]:
# Create another array of ones of shape (5, 3)

ones_1 = np.ones((5,3))
ones_1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
# Try add the array of ones and the other most recent array together

random_int + ones_1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [51]:
# Create another array of ones of shape (3, 5)

ones_2 = np.ones((3,5))
ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
# Subtract the new array of ones from the other most recent array

random_int - ones_2

array([[ 6.,  3.,  2.,  0.,  4.],
       [ 4., -1.,  7.,  4.,  1.],
       [ 2.,  2.,  1.,  8.,  1.]])

In [53]:
# Multiply the ones array with the latest array

random_int * ones_2

array([[7., 4., 3., 1., 5.],
       [5., 0., 8., 5., 2.],
       [3., 3., 2., 9., 2.]])

In [54]:
# Take the latest array to the power of 2 using '**'

random_int ** 2

array([[49, 16,  9,  1, 25],
       [25,  0, 64, 25,  4],
       [ 9,  9,  4, 81,  4]])

In [55]:
# Do the same thing with np.square()

np.square(random_int)

array([[49, 16,  9,  1, 25],
       [25,  0, 64, 25,  4],
       [ 9,  9,  4, 81,  4]])

In [56]:
# Find the mean of the latest array using np.mean()

np.mean(random_int)

np.float64(3.933333333333333)

In [58]:
# Find the maximum of the latest array using np.max()

np.max(random_int)

np.int64(9)

In [59]:
# Find the minimum of the latest array using np.min()

np.min(random_int)

np.int64(0)

In [60]:
# Find the standard deviation of the latest array

np.std(random_int)

np.float64(2.4890872936792627)

In [61]:
# Find the variance of the latest array

np.var(random_int)

np.float64(6.195555555555556)

In [62]:
# Reshape the latest array to (3, 5, 1)

random_int.reshape(3, 5, 1)

array([[[7],
        [4],
        [3],
        [1],
        [5]],

       [[5],
        [0],
        [8],
        [5],
        [2]],

       [[3],
        [3],
        [2],
        [9],
        [2]]])

In [63]:
# Transpose the latest array

random_int.T

array([[7, 5, 3],
       [4, 0, 3],
       [3, 8, 2],
       [1, 5, 9],
       [5, 2, 2]])

What does the transpose do?

In [65]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

random_int_1 = np.random.randint(10, size = (3,3))
print(random_int_1)

random_int_2 = np.random.randint(10, size = (3,2))
random_int_2

[[2 3 6]
 [3 8 0]
 [7 6 1]]


array([[7, 0],
       [8, 8],
       [1, 6]])

In [66]:
# Perform a dot product on the two newest arrays you created

random_int_1.dot(random_int_2)

array([[44, 60],
       [85, 64],
       [98, 54]])

In [72]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

random_int_1 = np.random.randint(10, size = (4,3))
print(random_int_1)

random_int_2 = np.random.randint(10, size = (4,3))
random_int_2

[[0 7 3]
 [5 7 3]
 [2 8 2]
 [8 1 1]]


array([[1, 5, 2],
       [8, 3, 0],
       [3, 0, 4],
       [3, 7, 7]])

In [73]:
# Perform a dot product on the two newest arrays you created

random_int_1.dot(random_int_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [74]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

random_int_2 = random_int_2.T

random_int_1.dot(random_int_2)

array([[41, 21, 12, 70],
       [46, 61, 27, 85],
       [46, 40, 14, 76],
       [15, 67, 28, 38]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [76]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

random_int_1 = np.random.randint(10, size = (3,3))
print(random_int_1)

random_int_2 = np.random.randint(10, size = (3,3))
random_int_2

[[2 3 2]
 [0 0 4]
 [5 2 8]]


array([[4, 7, 0],
       [4, 2, 0],
       [3, 4, 6]])

In [78]:
# Compare the two arrays with '>'

random_int_1 > random_int_2

array([[False, False,  True],
       [False, False,  True],
       [ True, False,  True]])

What happens when you compare the arrays with `>`?

In [79]:
# Compare the two arrays with '>='

random_int_1 >= random_int_2

array([[False, False,  True],
       [False, False,  True],
       [ True, False,  True]])

In [80]:
# Find which elements of the first array are greater than 7

random_int_1 > 7

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [81]:
# Which parts of each array are equal? (try using '==')

random_int_1 == random_int_2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [82]:
# Sort one of the arrays you just created in ascending order

np.sort(radnom_int_1)

array([[0, 2, 7, 8],
       [2, 5, 7, 8],
       [2, 3, 3, 7]])

In [85]:
# Sort the indexes of one of the arrays you just created

np.argsort(random_int_1)

array([[0, 2, 1],
       [0, 1, 2],
       [1, 0, 2]])

In [86]:
# Find the index with the maximum value in one of the arrays you've created

np.argmax(random_int_1)

np.int64(8)

In [87]:
# Find the index with the minimum value in one of the arrays you've created

np.argmin(random_int_1)

np.int64(3)

In [88]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

np.argmax(random_int_1, axis = 1)

array([1, 2, 2])

In [89]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

np.argmin(random_int_1, axis = 0)

array([1, 1, 0])

In [90]:
# Create an array of normally distributed random numbers

np.random.randn(4,3)

array([[-0.111204  , -1.74906943, -1.3414035 ],
       [-1.62169462, -1.14771997,  1.38960283],
       [-0.85524052, -1.02706176,  0.88283766],
       [-0.44930439,  0.41863947, -0.72817925]])

In [91]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.